'use client';

import { Printer } from 'lucide-react';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

interface Props {
  medications: string;
  instructions: string;
  doctorName: string;
  diagnosis: string;
  date: string;
  validUntil?: string;
}

export default function PrescriptionCard({ medications, instructions, doctorName, diagnosis, date, validUntil }: Props) {
  function handlePrint() {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>Prescription - SmartClinic</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 40px; max-width: 600px; margin: 0 auto; }
            h1 { color: #7c3aed; font-size: 24px; margin-bottom: 4px; }
            .meta { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
            .section { margin-bottom: 16px; }
            .label { font-size: 12px; color: #6b7280; text-transform: uppercase; font-weight: 600; margin-bottom: 4px; }
            .content { font-size: 14px; color: #111827; white-space: pre-wrap; }
            hr { border: none; border-top: 1px solid #e5e7eb; margin: 24px 0; }
            .footer { font-size: 12px; color: #9ca3af; text-align: center; margin-top: 40px; }
          </style>
        </head>
        <body>
          <h1>SmartClinic</h1>
          <p class="meta">Prescription &mdash; ${new Date(date).toLocaleDateString()}</p>
          <hr />
          <div class="section"><div class="label">Doctor</div><div class="content">Dr. ${doctorName}</div></div>
          <div class="section"><div class="label">Diagnosis</div><div class="content">${diagnosis}</div></div>
          <div class="section"><div class="label">Medications</div><div class="content">${medications}</div></div>
          <div class="section"><div class="label">Instructions</div><div class="content">${instructions}</div></div>
          ${validUntil ? `<div class="section"><div class="label">Valid Until</div><div class="content">${new Date(validUntil).toLocaleDateString()}</div></div>` : ''}
          <hr />
          <p class="footer">Generated by SmartClinic AI</p>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  }

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between">
          <div>
            <p className="font-semibold text-foreground">{diagnosis}</p>
            <p className="text-sm text-muted-foreground">Dr. {doctorName}</p>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-xs text-muted-foreground">{new Date(date).toLocaleDateString()}</span>
            <Button
              onClick={handlePrint}
              variant="ghost"
              size="icon"
              className="h-8 w-8"
            >
              <Printer className="w-4 h-4" />
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div className="bg-muted rounded-lg p-3">
            <p className="text-xs font-medium text-muted-foreground uppercase mb-1">Medications</p>
            <p className="text-sm text-foreground whitespace-pre-wrap">{medications}</p>
          </div>
          <div className="bg-muted rounded-lg p-3">
            <p className="text-xs font-medium text-muted-foreground uppercase mb-1">Instructions</p>
            <p className="text-sm text-foreground whitespace-pre-wrap">{instructions}</p>
          </div>
        </div>

        {validUntil && (
          <p className="text-xs text-muted-foreground mt-3">Valid until {new Date(validUntil).toLocaleDateString()}</p>
        )}
      </CardContent>
    </Card>
  );
}
